import '@/styles/globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import styles from '@/styles/utils.module.css'
import { Navbar } from '@nextui-org/react'
import Script from 'next/script'
import React from 'react'
import { formatSeconds } from './date'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function Layout({
  children, home
}: {
  children: React.ReactNode,
  home?: boolean
}) {
  const [timeSpent, setTimeSpent] = React.useState(0)
  
  React.useEffect(() => {
    const interval = setInterval(() => {
      setTimeSpent(timeSpent + 1)
    }, 1000)
    return () => clearInterval(interval)
  }, [timeSpent])

  const [isDark, setIsDark] = React.useState(false)
  const [theme, setTheme] = React.useState('light');

  React.useEffect(() => {
    const dark = localStorage.getItem('dark')
    if (dark) {
      setIsDark(dark === 'true')
    }
  }, [])

  React.useEffect(() => {
    localStorage.setItem('dark', isDark.toString())
  }, [isDark])

  React.useEffect(() => {
    if (isDark) {
      document.documentElement.classList.add('dark')
    } else {
      document.documentElement.classList.remove('dark')
    }
  }, [isDark])


  const toggleDark = () => {
    if (theme === 'light') {
      setTheme('dark');
    } else {
      setTheme('light');
    }
    setIsDark(!isDark)
  }

  return (
    <div className={styles.container}>
      {home && (
        <div>
          <h1 className={`${styles.heading2Xl} ${styles.header}`}>
            <img src="/corise_icon.png" alt="CoRise Learning" className={styles.logo} />
            <div>
              CoRise Learning
            </div>
          </h1>
        </div>
      )}
      <button onClick={toggleDark} className={styles.toggleDark}>Dark Mode</button>
      {children}
      {!home && (
        <div className={styles.backToHome}>
          <div>
            <p>Time spent on this page: {formatSeconds(timeSpent)} </p>
          </div>
          <a href="/">← Back to home</a>
        </div>
      )}
    </div>
  )
}
